version: '3.9'

services:
  db:
    image: postgres:13.3
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    env_file: 
      - ./.env
    ports:
      - 5432:5432

  redis: 
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:

